-- 사용자 프로필 테이블
-- Supabase auth.users 테이블과 1:1 관계를 맺습니다.
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  avatar_url TEXT,
  role TEXT NOT NULL DEFAULT 'user' -- 'user', 'company_rep', 'admin'
);

-- 사용자 프로필 정보 변경 시 함수를 통해 auth.users에도 반영되도록 설정
CREATE OR REPLACE FUNCTION public.update_public_user_data()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.profiles
  SET 
    full_name = NEW.raw_user_meta_data->>'full_name',
    avatar_url = NEW.raw_user_meta_data->>'avatar_url'
  WHERE id = NEW.id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- auth.users 테이블에 변경이 생길 때마다 위 함수를 트리거
CREATE TRIGGER on_auth_user_updated
  AFTER UPDATE ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.update_public_user_data();


-- 업종 카테고리 테이블
CREATE TABLE public.industries (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 회사 정보 테이블
CREATE TABLE public.companies (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  description TEXT,
  industry_id BIGINT REFERENCES public.industries(id),
  founded_date DATE,
  website TEXT,
  logo_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

-- 재무 데이터 테이블
CREATE TABLE public.financial_data (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  year INT NOT NULL,
  revenue NUMERIC,
  operating_income NUMERIC,
  net_income NUMERIC,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(company_id, year)
);

-- 회사 문서 테이블
CREATE TABLE public.company_documents (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  document_name TEXT NOT NULL,
  document_url TEXT NOT NULL,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 커뮤니티 게시글 테이블
CREATE TABLE public.posts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  content TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

-- 댓글 테이블
CREATE TABLE public.comments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Q&A 질문 테이블
CREATE TABLE public.questions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  content TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Q&A 답변 테이블
CREATE TABLE public.answers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 공지사항 테이블
CREATE TABLE public.notices (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  author_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL, -- 관리자
  title TEXT NOT NULL,
  content TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 초기 데이터 삽입 (예시)
INSERT INTO public.industries (name) VALUES
('정보기술(IT)'),
('바이오/헬스케어'),
('금융'),
('제조업'),
('서비스업');
